// data.js

export const data = {
  tickets: [
    {
      id: "CAM-1",
      title: "Update User UI",
      tag: ["Feature request"],
      userId: "user-1",
      status: "Todo",
      statusIcon: "/svg/To-do.svg",
      statusIcon1: "/svg/3 dot menu.svg",
      priority: 4,
    },
    {
      id: "CAM-2",

      title:
        "Add Multi-Language Support - Enable multi-language support.",
      tag: ["Feature Request"],
      userId: "user-2",
      status: "In progress",
      statusIcon: "/svg/in-progress.svg",
      statusIcon1: "/svg/3 dot menu.svg",
      priority: 3,
    },
    {
      id: "CAM-3",
      title: "Optimizing  Queries",
      tag: ["Feature Request"],
      userId: "user-2",
      status: "In progress",
      statusIcon: "/svg/in-progress.svg",
      statusIcon1: "/svg/3 dot menu.svg",
      priority: 1,
    },
    {
      id: "CAM-4",
      title: "Email",
      tag: ["Feature Request"],
      userId: "user-1",
      status: "In progress",
      statusIcon: "/svg/in-progress.svg",
      statusIcon1: "/svg/3 dot menu.svg",
      priority: 3,
    },
    {
      id: "CAM-5",
      title: "Functionality",
      tag: ["Feature Request"],
      userId: "user-5",
      status: "In progress",
      statusIcon: "/svg/in-progress.svg",
      statusIcon1: "/svg/3 dot menu.svg",
      priority: 0,
    },
    {
      id: "CAM-6",
      title: "Payment Gateway",
      tag: ["Feature Request"],
      userId: "user-2",
      status: "Todo",
      statusIcon: "/svg/To-do.svg",
      statusIcon1: "/svg/3 dot menu.svg",
      priority: 1,
    },
    {
      id: "CAM-7",
      title: "Create Onboarding Tutorial for New Users",
      tag: ["Feature Request"],
      userId: "user-1",
      status: "Done",
      statusIcon: "/svg/Done.svg",
      statusIcon1: "/svg/3 dot menu.svg",
      priority: 2,
    },
    {
      id: "CAM-8",
      title: "Implement Role-Based Access Control (RBAC)",
      tag: ["Feature Request"],
      userId: "user-3",
      status: "In progress",
      statusIcon: "/svg/in-progress.svg",
      statusIcon1: "/svg/3 dot menu.svg",
      priority: 3,
    },
    {
      id: "CAM-9",
      title: "Upgrade Server Infrastructure",
      tag: ["Feature Request"],
      userId: "user-5",
      statusIcon: "/svg/To-do.svg",
      statusIcon1: "/svg/3 dot menu.svg",
      status: "Todo",
      priority: 2,
    },
    {
      id: "CAM-10",
      tag: ["Feature Request"],
      userId: "user-4",
      status: "Canceled",
      statusIcon: "/svg/Cancelled.svg",
      statusIcon1: "/svg/3 dot menu.svg",
      priority: 0,
    },
    {
      id: "CAM-11",
      title: "Conduct Security Assessment",
      tag: ["Feature Request"],
      userId: "user-4",
      status: "Done",
      statusIcon: "/svg/Done.svg",
      statusIcon1: "/svg/3 dot menu.svg",
      priority: 1,
    },
    {
      id: "CAM-12",
      title: "Conduct Security Assessment",
      tag: ["Feature Request"],
      userId: "user-4",
      status: "Done",
      statusIcon: "/svg/Done.svg",
      statusIcon1: "/svg/3 dot menu.svg",
      priority: 1,
    },
    {
      id: "CAM-13",
      title: "Upgrade Server Infrastructure",
      tag: ["Feature Request"],
      userId: "user-5",
      statusIcon: "/svg/To-do.svg",
      statusIcon1: "/svg/3 dot menu.svg",
      status: "Todo",
      priority: 2,
    },
    {
      id: "CAM-14",
      title: "Upgrade Server Infrastructure",
      tag: ["Feature Request"],
      userId: "user-5",
      statusIcon: "/svg/To-do.svg",
      statusIcon1: "/svg/3 dot menu.svg",
      status: "Todo",
      priority: 2,
    },
    {
      id: "CAM-15",
      title: "Third-Party Payment Gateway",
      tag: ["Feature Request"],
      userId: "user-2",
      status: "Todo",
      statusIcon: "/svg/To-do.svg",
      statusIcon1: "/svg/3 dot menu.svg",
      priority: 1,
    },
  ],
  users: [
    { id: "user-1", name: "Rahul Mishra", available: false },
    { id: "user-2", name: "Rohan", available: true },
    { id: "user-3", name: "Nandini Shankar ", available: true },
    { id: "user-4", name: "Shreya Bhushan", available: true },
    { id: "user-5", name: "Sureshita Raina", available: true },
  ],
};
